version: "3.8"

services:
  servicio-chat:
    image: llm_connector
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ../llm_connector/.env

  servicio-cnn:
    image: cnn_image
    ports:
      - "8002:8002"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ../cnn_image/.env

  servicio-linear:
    image: ml_model
    ports:
      - "8003:8003"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ./.env

  gradio-gui:
    image: gradio-gui
    ports:
      - "7860:7860"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - url=http://servicio-chat:8000/chat
      - model_url=http://servicio-linear:8003/model/linear/prediction
      - CNN_URL=http://servicio-cnn:8002/api/cnn/classify
